'use client';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import {NextUIProvider} from "@nextui-org/react";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en">
    <body className={`${inter.className} flex flex-col min-h-screen`}>
        <NextUIProvider>
            <div className="relative flex flex-grow flex-col">
            {children}
            </div>
        </NextUIProvider>
    </body>
  </html>
  );
}
